version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: "portainer"
    restart: unless-stopped
    volumes:
    - "/saturn/data/portainer:/data"
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "9000:80"
    networks:
    - "local"

  watchtower:
    image: v2tec/watchtower:armhf-0.3
    container_name: "watchtower"
    command: --cleanup
    networks:
    - "local"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

  mysql:
    image: hypriot/rpi-mysql
    container_name: "watchtower"
    restart: unless-stopped
    networks:
    - "local"
    volumes:
    - "/docker/data/mysql:/var/lib/mysql"

  discord-irc:
    image: jekotia/discord-irc
    container_name: "discord-irc"
    restart: unless-stopped
    volumes:
    - "/saturn/data/discord-irc:/data"
    networks:
    - "local"

  gogs:
    image: gogs/gogs-rpi
    container_name: "gogs"
    restart: unless-stopped
    volumes:
    - /saturn/data/gogs:/data
    ports:
    - "10022:22"
    - "10080:3000"
    networks:
    - "local"
    depends_on:
    - "mysql"

#  hass:
#    image:
#    container_name: "hass"
#    restart: unless-stopped
#    volumes:
#    - /saturn/data/hass:/data
#    ports:
#    -
#    networks:
#    - local

#nginx
#  nginx:
#    image: jekotia/nginx
#    container_name: "nginx"
#    restart: unless-stopped
#    volumes:
#    - /saturn/data/nginx/conf:/etc/nginx:ro
#    - /saturn/data/nginx/www:/var/www:ro
#    - /saturn/data/nginx/logs:/var/log/nginx
#    - /saturn/data/cert:/cert:ro
#    ports:
#    - 80:80
#    - 443:443
#    networks:
#    - local

#  pivpn:
#    image:
#    container_name: "pivpn"
#    restart: unless-stopped
#    volumes:
#    - /saturn/data/pivpn:/data
#    ports:
#    -
#    networks:
#    - local

#  pihole:
#    image:
#    container_name: "pihole"
#    restart: unless-stopped
#    volumes:
#    - /saturn/data/pihole:/data
#    ports:
#    -
#    networks:
#    - local

  weechat:
    image: jekotia/weechat
    container_name: "weechat"
    restart: unless-stopped
    volumes:
    - "/saturn/data/weechat:/data"
    ports:
    - "9001:9001"
    - "8443:8443"
    networks:
    - local
    stdin_open: true
    tty: true

networks:
  local:
    driver: bridge
