version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: "portainer"
    restart: unless-stopped
    volumes:
    - "/saturn/data/portainer:/data"
    - "/var/run/docker.sock:/var/run/docker.sock"
#    ports:
#    - "9000:80"
    networks:
    - "proxy"

  watchtower:
    image: v2tec/watchtower:armhf-0.3
    container_name: "watchtower"
    restart: unless-stopped
    command: --cleanup
#    networks:
#    - "local"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
#The e-mail address from which notifications will be sent.
    - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
#The e-mail address to which notifications will be sent.
    - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL_TO}
# The SMTP server to send e-mails through.
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
# Do not verify the TLS certificate of the mail server. This should be used only for testing.
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=false
# The port used to connect to the SMTP server to send e-mails through. Defaults to 25.
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
# The username to authenticate with the SMTP server with.
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL_FROM}
# The password to authenticate with the SMTP server with.
    - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_FROM_PASSWORD}

  mysql:
    image: hypriot/rpi-mysql
    container_name: "mysql"
    networks:
    - "local"
    volumes:
    - "/docker/data/mysql:/var/lib/mysql"
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${DB_USER}
    - MYSQL_USER_PASSWORD=${DB_PASSWORD}
    - MYSQL_USER_PASSWORD=${DB_DATABASE}

  alerthub:
    image: jekotia/alerthub
    container_name: "alerthub"
    restart: unless-stopped
    volumes:
    - "/saturn/data/alerthub/config.js:/data/config.js:ro"
#    networks:
#    - "out"

  discord-irc:
    image: jekotia/discord-irc
    container_name: "discord-irc"
    restart: unless-stopped
    volumes:
    - "/saturn/data/discord-irc:/data"
#    networks:
#    - "local"

  gogs:
    image: gogs/gogs-rpi
    container_name: "gogs"
    restart: unless-stopped
    volumes:
    - /saturn/data/gogs:/data
    ports:
    - "10022:22"
    - "3000:3000"
    networks:
    - "proxy"
    - "local"
    depends_on:
    - "mysql"

  hass:
    image: homeassistant/raspberrypi3-homeassistant:0.68.1
    container_name: "hass"
    restart: unless-stopped
    volumes:
    - /saturn/data/hass:/config
    - /etc/localtime:/etc/localtime:ro
#    - /saturn/data/hass:/data
    ports:
    - 3580:80
    networks:
    - proxy

  nginx-proxy:
    image: jekotia/nginx-proxy
    container_name: "proxy"
    restart: unless-stopped
    environment:
    - API_KEY=${AMPLIFY_API_KEY}
    - AMPLIFY_IMAGENAME=${AMPLIFY_IMAGENAME}
    volumes:
    - /saturn/data/proxy:/etc/nginx:ro
#    - /saturn/data/nginx/www:/var/www:ro
#    - /saturn/data/nginx/logs:/var/log/nginx
    - /saturn/data/ssl:/cert:ro
    ports:
    - 80:80
    - 443:443
    networks:
    - proxy

  pihole:
    image: diginc/pi-hole-multiarch:debian_armhf
    container_name: "pihole"
    restart: unless-stopped
    volumes:
    - "/saturn/data/pihole/etc:/etc/pihole"
    - "/saturn/data/pihole/dnsmasq.d:/etc/dnsmasq.d"
    ports:
    - "5080:80"
    - "53:53"
    networks:
    - proxy
    environment:
# Set to your server's external IP to block ads fully
    - ServerIP=192.168.0.5
# If you have a v6 network set to your server's external IPv6 to block IPv6 ads fully
    - ServerIPv6=
# Set your timezone to make sure logs rotate at local midnight instead of at UTC midnight.
# See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    - TZ=CA
# http://pi.hole/admin password. Run `docker logs pihole | grep random` to find your random pass.
    - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
# Primary upstream DNS provider, default is google DNS
    - DNS1=8.8.8.8
# Secondary upstream DNS provider, default is google DNS
    - DNS2=8.8.4.4
# What your web server 'virtual host' is, accessing admin through this Hostname/IP allows you to make
# changes to the whitelist / blacklists in addition to the default 'http://pi.hole/admin/' address
    - VIRTUAL_HOST=
# For unraid compatibility, strips out all the IPv6 configuration from DNS/Web services when false
    - IPv6=False
# The default works fine with our basic example docker run commands.
# If you're trying to use DHCP with --net host mode then you may have to customize this or DNSMASQ_LISTENING.
    - INTERFACE=
# local listens on all local subnets
# all permits listening on internet origin subnets in addition to local.
    - DNSMASQ_LISTENING=
# This will break the 'webpage blocked' functionality of pi-hole however it may help advanced setups
# like those running synology or --net=host docker argument.
    - WEB_PORT=

  weechat:
    image: jekotia/weechat
    container_name: "weechat"
    restart: unless-stopped
    volumes:
    - "/saturn/data/weechat:/data"
    ports:
#    - "9001:9001"
    - "8443:8443"
#    networks:
#    - proxy
    stdin_open: true
    tty: true

networks:
  proxy:
    driver: bridge
  local:
    driver: bridge
